title: "Boost Behavioral Data -> AF"
description: "A blog showcasing various subjects post-QC."
baseurl: "/boost-beh-AF" # If your site is at https://username.github.io, leave it empty. If at https://username.github.io/repo-name, set it to "/repo-name"
url: "https://hbclab.github.io" # Replace with your GitHub Pages URL
repository: "HBClab/boost-beh-AF" # Replace with your GitHub repository in "owner/re
